<p style="font-family: Arial; font-size:3.75em;color:blue; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.
- Input/Output: simplifies reading and writing of data from/to file.

<b>Additional Recommended Resources:</b>
"https://docs.scipy.org/doc/numpy/reference/


<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Getting started with ndarray<br><br></p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Create Rank 1 numpy arrays:
</p>

In [1]:
import numpy as np

array_1d = np.array([31, 5, 45])

The type of an ndarray is: "<class 'numpy.ndarray'>"

In [2]:
print(type(array_1d))              

<class 'numpy.ndarray'>


the shape of the array should have just one dimension (Rank 1)

In [3]:
print(array_1d.shape)

(3,)


this is a 1-rank array, thus only one index is needed to accesss each element

In [4]:
print(array_1d[0], array_1d[1], array_1d[2]) 

31 5 45


ndarrays are mutable i.e. elements of the array can be changed

In [5]:
array_1d[0] =888            

print(array_1d)

[888   5  45]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Create a Rank 2 numpy array:</p>

A rank 2 **ndarray** is one with two dimensions.  

Notice the format below of [ [row] , [row] ].  2 dimensional arrays may be used for representing matrices/datasets.

In [6]:
array_2d = np.array([[11,12,13],[21,22,23]])

print(array_2d)  # print the array

[[11 12 13]
 [21 22 23]]


In [7]:
print("The shape of the array is 2r*3c: ", array_2d.shape)

The shape of the array is 2r*3c:  (2, 3)


In [8]:
print("Accessing elements at position [0,0], [0,1], [1,0] and [1,2] of the ndarray: ", 
      array_2d[0, 0], ", ",
      array_2d[0, 1],", ", 
      array_2d[1, 0],", ",
      array_2d[1, 2] )

Accessing elements at position [0,0], [0,1], [1,0] and [1,2] of the ndarray:  11 ,  12 ,  21 ,  23


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Creating ndarrays with numpy methods:
</p>

Generally we will not be creating array using the above methods. numpy has a number of built in methods which can quickly create multidimensional arrays.

### Create a 2x2 array of zeros

In [9]:
nd_0 = np.zeros((2,2))      
print(nd_0)                              

[[0. 0.]
 [0. 0.]]


### create a 2x2 array filled with  value 5

In [10]:
nd_5 = np.full((2,2), 5.0)  
print(nd_5)   

[[5. 5.]
 [5. 5.]]


### create a 2x2 matrix with the diagonal 1s and the others 0

In [11]:
nd_1d = np.eye(2,2)
print(nd_1d)  

[[1. 0.]
 [0. 1.]]


### create an array of ones

In [12]:
nd_1 = np.ones((1,2))
print(nd_1)    

[[1. 1.]]


the above ndarray is a rank 2 array

In [13]:
print(nd_1.shape)

(1, 2)


In [14]:
print(nd_1[0,1])

1.0


### create an array of random floats between 0 and 1

In [15]:
nd_rand = np.random.random((3,3))
print(nd_rand)    

[[0.03631732 0.104482   0.67622883]
 [0.98941998 0.82149756 0.80550212]
 [0.59314795 0.61699746 0.36501122]]


<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Array Indexing
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C1; font-style:bold"><br>
Slice indexing:
</p>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays. Create Rank 2 array of shape (3, 4)

In [16]:
nd_rand = np.random.random((3,4))
print(nd_rand)

[[0.14411951 0.47095552 0.01381074 0.05176954]
 [0.68687431 0.89394702 0.84946897 0.4634564 ]
 [0.76322086 0.89639912 0.90923879 0.04454717]]


Use array slicing to get a subarray consisting of the first 3 rows x 3 columns.

In [17]:
slice_nd = nd_rand[0:3, 0:3]
print(slice_nd)

[[0.14411951 0.47095552 0.01381074]
 [0.68687431 0.89394702 0.84946897]
 [0.76322086 0.89639912 0.90923879]]


Modifying a slice will lead to modifying the underlying array

In [18]:
print("Before:", nd_rand[0, 1])
slice_nd[0, 1] = 1000
print("After:", nd_rand[0, 1])    

Before: 0.47095551817647374
After: 1000.0


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Using both integer indexing & slice indexing
</p>

Combinations of integer indexing and slice indexing can be used to create different shaped matrices. 
Create a Rank 2 array of shape (3, 4)

In [19]:
an_array = np.array([[10,14,16,18], [24,26,28,29], [30,33,36,38]])
print(an_array)

[[10 14 16 18]
 [24 26 28 29]
 [30 33 36 38]]


Using both integer indexing & slicing generates an array of lower rank

In [20]:
row_rank1 = an_array[1,:]

print("\nRank 1 view. \n\n", row_rank1, "\n\nNotice only a single []")
print("The dimension is", row_rank1.shape) 


Rank 1 view. 

 [24 26 28 29] 

Notice only a single []
The dimension is (4,)


Slicing alone will generate an array of the same rank as the an_array

In [21]:
row_rank2 = an_array[1:2, :]

print("\nRank 2 view. \n\n", row_rank2, "\n\nNotice double [ [] ]")
print("The dimension is", row_rank2.shape)  


Rank 2 view. 

 [[24 26 28 29]] 

Notice double [ [] ]
The dimension is (1, 4)


#### Exercise: Create  rank 1 and rank 2 column arrays using slicing

In [22]:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)


[14 26 33] (3,)

[[14]
 [26]
 [33]] (3, 1)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Array Indexing for changing elements:
</p>

It at times may be useful to use an array of indexes to access elements or change elements.

In [23]:
an_array = np.array([[10,14,17], [25,27,29], [33,36,39], [40,45,47]])

print('Original Array:')
print(an_array)

Original Array:
[[10 14 17]
 [25 27 29]
 [33 36 39]
 [40 45 47]]


Creating an array of indices

In [24]:
col_indices = np.array([0, 1, 2, 2])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 2]

Rows indices picked :  [0 1 2 3]


The pairings of row_indices and col_indices is shown below.  We will change the elements at these indexes.

In [25]:
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  2


Selecting one element from each row


In [26]:
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [10 27 39 47]


Change one element from each row using the indices selected

In [27]:
an_array[row_indices, col_indices] += 10000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[10010    14    17]
 [   25 10027    29]
 [   33    36 10039]
 [   40    45 10047]]


<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Boolean Indexing
<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Array Indexing for changing elements:
</p>

In [28]:
an_array = np.array([[16,18], [26, 29], [35, 37]])
print(an_array)

[[16 18]
 [26 29]
 [35 37]]


create a filter to find elements greater than 15. The filter will be boolean values for whether each element meets the condition or not.

In [29]:
filter = (an_array > 15)
filter

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

The `filter` is of the same size ndarray as `an_array` which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15. Now, we can now select just those elements which meet that criteria

In [30]:
print(an_array[filter])

[16 18 26 29 35 37]


We can apply filter directly as below:

In [31]:
an_array[(an_array % 2 == 0)]

array([16, 18, 26])

We can change the elements in the array by applying filter logic.

In [32]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[116 118]
 [126  29]
 [ 35  37]]


<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Datatypes:
</p>

Python assigns the  data type itself.

In [33]:
ex1 = np.array([11, 12]) 
print(ex1.dtype)

int64


In [34]:
ex2 = np.array([11.0, 12.0]) 
print(ex2.dtype)

float64


We can explicitely mention the data type as well.

In [35]:
ex3 = np.array([11, 21], dtype=np.int64) 
print(ex3.dtype)

int64


We can force data types as well. floats into integers

In [36]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype, ex4)

int64 [11 12]


In [37]:
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)

print(ex5)

float64
[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Arithmetic Array Operations:
</p>

In [38]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


<p style="font-family: Arial; font-size:1.5em;color:#2462C0; font-style:bold"><br>
Adding numbers
</p>

In [39]:
print(x + y)        

[[322.1 324.1]
 [342.1 344.1]]


In [40]:
print(np.add(x, y))

[[322.1 324.1]
 [342.1 344.1]]


<p style="font-family: Arial; font-size:1.5em;color:#2462C0; font-style:bold"><br>
Substracting numbers
</p>

In [41]:
print(x - y)

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [42]:

print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]


<p style="font-family: Arial; font-size:1.5em;color:#2462C0; font-style:bold"><br>
Multiplying numbers
</p>

In [43]:
print(x * y)

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [44]:
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]


<p style="font-family: Arial; font-size:1.5em;color:#2462C0; font-style:bold"><br>
Divide numbers
</p>

In [45]:
print(x / y)

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [46]:
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


<p style="font-family: Arial; font-size:1.5em;color:#2462C0; font-style:bold"><br>
Square root
</p>

In [47]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


<p style="font-family: Arial; font-size:1.5em;color:#2462C0; font-style:bold"><br>
Exponentiation
</p>

In [48]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Statistical Methods, Sorting, and Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Basic Statistical Operations:
</p>

In [49]:
arr = 10 * np.random.randn(3,4)
print(arr)

[[-2.02110535 -6.75612415 -8.01109478  2.44395504]
 [-0.9696147   5.75848721  3.98034516  1.73619718]
 [ 0.69262853 10.8221384  -2.36928358 -3.50137698]]


The mean for all elements is

In [50]:
print(arr.mean())

0.1504293321821207


Row wise mean



In [51]:
print(arr.mean(axis = 1))

[-3.58609231  2.62635371  1.41102659]


Column wise mean

In [52]:
print(arr.mean(axis = 0))

[-0.76603051  3.27483382 -2.1333444   0.22625842]


Sum of elements

In [53]:
print(arr.sum())

1.8051519861854484


Row wise Median

In [54]:
print(np.median(arr, axis = 1))

[-4.38861475  2.85827117 -0.83832753]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Sorting:
</p>


In [55]:
unsorted = np.random.randn(15)

print(unsorted)

[ 0.36509059 -2.18736522 -0.03779312 -1.87037099 -1.24446422 -0.34715737
 -1.46245708 -0.21524023 -0.24849605 -0.18865914  0.30755644  2.29542735
  0.19772193  0.81659989  0.90977471]


In [56]:
sorted = np.array(unsorted)
sorted.sort()

print(sorted)

[-2.18736522 -1.87037099 -1.46245708 -1.24446422 -0.34715737 -0.24849605
 -0.21524023 -0.18865914 -0.03779312  0.19772193  0.30755644  0.36509059
  0.81659989  0.90977471  2.29542735]


Sorting in place

In [57]:
unsorted.sort() 

print(unsorted)

[-2.18736522 -1.87037099 -1.46245708 -1.24446422 -0.34715737 -0.24849605
 -0.21524023 -0.18865914 -0.03779312  0.19772193  0.30755644  0.36509059
  0.81659989  0.90977471  2.29542735]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Finding Unique elements:
</p>

In [58]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Set Operations with np.array data type:
</p>

In [59]:
s1 = np.array(['data','science','AI'])
s2 = np.array(['ML','AI','data'])
print(s1, s2)

['data' 'science' 'AI'] ['ML' 'AI' 'data']


In [60]:
print( np.intersect1d(s1, s2) ) 

['AI' 'data']


In [61]:
print( np.union1d(s1, s2) )

['AI' 'ML' 'data' 'science']


Element of s1 which are not in s2

In [62]:
print( np.setdiff1d(s1, s2) )

['science']


Element of s1 which is also in s2

In [63]:
print( np.in1d(s1, s2) )

[ True False  True]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>
Binary Format:</p>

In [64]:
x = np.array([ 23.23, 24.24] )

In [65]:
np.save('an_array', x)

In [66]:
np.load('an_array.npy')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>
Text Format:</p>

In [67]:
np.savetxt('array.txt', X=x, delimiter=',')

In [68]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Dot Product on Matrices and Inner Product on Vectors:
</p>

Dot product of two matrices

In [69]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

In [70]:
print(x2d.dot(y2d))

[[4 4]
 [4 4]]


In [71]:
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]


inner product of two vectors

In [72]:
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

In [73]:
print(a1d.dot(b1d))

180


In [74]:
print(np.dot(a1d, b1d))

180


Dot produce on an array and vector

In [75]:
print(x2d.dot(a1d))

[18 18]


In [76]:
print(np.dot(x2d, a1d))

[18 18]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Sum:
</p>

sum elements in the array



In [77]:
ex1 = np.array([[10,12],[20,22]])

print(ex1)

[[10 12]
 [20 22]]


In [78]:
print(np.sum(ex1))

64


Column wise sum

In [79]:
print(np.sum(ex1, axis=0))

[30 34]


Row wise sum

In [80]:
print(np.sum(ex1, axis=1))

[22 42]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Element-wise Functions: </p>

Comparing two arrays values to get the maximum of each.

In [81]:
x1 = np.random.randn(10)
x1

array([-0.77927993, -1.57277968, -0.76287069,  1.5524336 , -0.56050903,
       -1.21731509,  1.06893149,  2.13350936, -0.35299958,  0.64019242])

In [82]:
y1 = np.random.randn(10)
y1

array([ 1.35248703,  0.81843476, -0.19506389, -1.25751329,  0.03885044,
        1.94467113, -0.21411698,  1.47462944, -1.22860757, -0.67553205])

Element wise maximum between two arrays is

In [83]:

np.maximum(x1, y1)

array([ 1.35248703,  0.81843476, -0.19506389,  1.5524336 ,  0.03885044,
        1.94467113,  1.06893149,  2.13350936, -0.35299958,  0.64019242])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Reshaping array:
</p>

Values from 0 through 19 in an array

In [84]:
arr = np.arange(25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


Reshape to 5*5 matrix

In [85]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Transpose:

</p>

In [86]:
ex1 = np.array([[10,12],[20,22]])
print(ex1)
ex1.T

[[10 12]
 [20 22]]


array([[10, 20],
       [12, 22]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Indexing using where():</p>

In [87]:
x1 = np.array([1,2,3,4,5])

y1 = np.array([10,21,35,44,50])

filter = np.array([True, False, True, False, True])

In [88]:
out = np.where(filter, x1, y1)
print(out)

[ 1 21  3 44  5]


In [89]:
matrix1 = np.random.rand(5,5)
matrix1

array([[0.2043464 , 0.59718759, 0.57874124, 0.85000981, 0.78350412],
       [0.35802022, 0.43392956, 0.32574981, 0.30871216, 0.89706555],
       [0.9325494 , 0.89194835, 0.66859454, 0.27928877, 0.88300234],
       [0.19252489, 0.33933505, 0.53935911, 0.13822902, 0.13010643],
       [0.30177132, 0.11283097, 0.22887111, 0.47491019, 0.99776014]])

In [90]:
np.where( matrix1 > 0.5, 1000, -1)

array([[  -1, 1000, 1000, 1000, 1000],
       [  -1,   -1,   -1,   -1, 1000],
       [1000, 1000, 1000,   -1, 1000],
       [  -1,   -1, 1000,   -1,   -1],
       [  -1,   -1,   -1,   -1, 1000]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
"any" or "all" conditionals:</p>

In [91]:
arr_bools = np.array([ True, False, True, True, False ])

In [92]:
arr_bools.any()

True

In [93]:
arr_bools.all()

False

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Random Number Generation:
</p>

Normal distribution

In [94]:
Y = np.random.normal(size = (2,5)) #2D array
print(Y)

[[-0.95257098  0.21273645  0.96477026 -1.87750654 -0.02769458]
 [-0.23531204  1.72307531 -0.90164182  0.82560862 -1.22745838]]


In [95]:
np.random.normal(size=4) #1D array

array([ 0.76104143,  0.24138716, -0.28092669,  0.00231672])

Random intergers

In [96]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[12 23 23 44]


new ordering of elements in Z

In [97]:
np.random.permutation(Z)

array([23, 23, 12, 44])

Uniform distribution

In [98]:
np.random.uniform(size=4)

array([0.02663377, 0.029237  , 0.85732612, 0.19332462])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Merging data sets:
</p>

In [99]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

M = np.random.randint(low=2,high=50,size=(2,2))
print("\n",M)

[[27 28]
 [18 38]]

 [[25  6]
 [17 10]]


In [100]:
np.vstack((K,M))

array([[27, 28],
       [18, 38],
       [25,  6],
       [17, 10]])

In [101]:
np.hstack((K,M))

array([[27, 28, 25,  6],
       [18, 38, 17, 10]])

In [102]:
np.concatenate([K, M], axis = 0)

array([[27, 28],
       [18, 38],
       [25,  6],
       [17, 10]])

In [103]:
np.concatenate([K, M.T], axis = 1)

array([[27, 28, 25, 17],
       [18, 38,  6, 10]])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [104]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

create the ndarray with values 0,1,2...,size-1

In [105]:
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


create the list with values 0,1,2...,size-1

In [106]:
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


timer expects an operation as a parameter. Ex, Sum the numbers using nd.sum

In [107]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000594 seconds


In [108]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.006426 seconds


<p style="font-family: Arial; font-size:2.75em;color:blue; font-style:bold"><br>
Broadcasting:Introduction to broadcasting
<br><br>
</p>


For more details:

https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm

In [109]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [110]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [111]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [112]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [113]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [114]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


End of Document
***